<a href="https://colab.research.google.com/github/maharajsreeraam/groupcodesof214519/blob/main/CIE_3___214519_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

Exercise-2

In [ ]:
import numpy as np
print(np.__version__) 
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

Exercise-3

In [ ]:
import numpy as np
Z = np.zeros(10) 
print(Z) 




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Exercise-4

In [ ]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
Z = np.zeros(10) 
Z[5] = 2 
print(Z) 


[0. 0. 0. 0. 0. 2. 0. 0. 0. 0.]


In [ ]:
Z = np.arange(20,50) 
print(Z) 


[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [ ]:
Z = np.arange(50) 
Z[::-1] 


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
Z = np.arange(9).reshape(3,3) 
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


Exercise-10

In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Exercise-11

In [ ]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.83872722 0.72931184 0.43787498]
  [0.44719527 0.97688515 0.44279211]
  [0.87564006 0.83325934 0.82837973]]

 [[0.55144577 0.70225548 0.18665083]
  [0.58724493 0.48295483 0.6381489 ]
  [0.65216714 0.67383747 0.18711105]]

 [[0.28072657 0.94923364 0.76618248]
  [0.98362719 0.19023442 0.12250561]
  [0.49106761 0.57762108 0.14881921]]]


Exercise-12

In [ ]:
Z = np.random.random((10,10))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

[[0.16189584 0.50575723 0.0537293  0.12253594 0.83411932 0.34006094
  0.01727421 0.30725442 0.28146674 0.40487759]
 [0.45615227 0.71109881 0.07023555 0.50102184 0.69917754 0.61033765
  0.4791942  0.60928028 0.2983793  0.69936112]
 [0.58181094 0.22851674 0.63348995 0.58180965 0.65640054 0.40621607
  0.03703532 0.95484036 0.38477928 0.53672952]
 [0.84443117 0.11086394 0.16788903 0.65604075 0.40037017 0.01491978
  0.97469814 0.08649354 0.25696141 0.7189334 ]
 [0.46109349 0.75914963 0.39210626 0.06840445 0.16474603 0.65108513
  0.54367103 0.33059165 0.0324063  0.7698414 ]
 [0.79435424 0.77711709 0.02782988 0.40794359 0.14561257 0.16194776
  0.73277521 0.0625606  0.79579685 0.69081332]
 [0.81753288 0.77419249 0.74679353 0.13405246 0.59667643 0.80869201
  0.97895656 0.88461045 0.43433227 0.55483528]
 [0.07181995 0.47212708 0.35003323 0.08471504 0.59622032 0.17158773
  0.73668726 0.36884274 0.63509903 0.1194443 ]
 [0.87417941 0.06099371 0.65526328 0.86331111 0.55099622 0.60017749
  0.23827451

Exercise-13

In [ ]:
Z = np.random.random(20) 
m = Z.mean() 
print(m)


0.47109583862641385


Exercise-14

In [ ]:
Z = np.ones((10,10)) 
Z[1:-1,1:-1] = 0 


Exercise-15

In [ ]:
import numpy as np
0 * np.nan 
np.nan == np.nan 
np.inf > np.nan 
np.nan - np.nan 
0.3 == 3 * 0.1 


False

Exercise-16

In [ ]:
Z = np.diag(1+np.arange(4),k=-1) 
print(Z) 


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Exercise-17

In [ ]:
import numpy as np

In [ ]:
Z = np.zeros((8,8),dtype=int) 
Z[1::2,::2] = 1 
Z[::2,1::2] = 1 
print(Z) 


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Exercise-18

In [ ]:
print(np.unravel_index(100,(6,7,8))) 


(1, 5, 4)


Exercise-19

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4)) 
print(Z) 


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Exercise-20

In [ ]:
Z = np.random.random((5,5)) 
Zmax, Zmin = Z.max(), Z.min() 
Z = (Z - Zmin)/(Zmax - Zmin) 
print(Z) 


[[0.08188229 1.         0.42731889 0.45880991 0.84091554]
 [0.82161523 0.         0.89721332 0.09221291 0.3013733 ]
 [0.70908716 0.92500281 0.58246459 0.4900201  0.70566889]
 [0.93384672 0.19638451 0.52001085 0.15971426 0.78837178]
 [0.9780057  0.8278211  0.8019057  0.27045547 0.10289927]]


Exercise-21

In [ ]:
color = np.dtype([("r", np.ubyte, 1), 
("g", np.ubyte, 1), 
("b", np.ubyte, 1), 
("a", np.ubyte, 1)]) 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


Exercise-22

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2))) 
print(Z) 


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Exercise-23

In [ ]:
import numpy as np
Z = np.arange(11) 
Z[(3 < Z) & (Z <= 8)]


array([4, 5, 6, 7, 8])

Exercise-24

In [ ]:
print(sum(range(5),-1)) 
from numpy import * 
print(sum(range(5),-1)) 



9
10


Exercise-25

In [ ]:
import numpy as np
Z**Z 
2 << Z >> 2 
Z <- Z 
1j*Z 
Z/1/1 



array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Exercise-26

In [ ]:
np.array(0) // np.array(0) 
np.array(0) // np.array(0.) 
np.array(0) / np.array(0) 
np.array(0) / np.array(0.) 

 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in floor_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


nan

Exercise-27

In [ ]:
Z = np.random.uniform(-10,+10,10) 
print (np.trunc(Z + np.copysign(0.5, Z))) 


[ -9.   7.  -1.  -9. -10.   3.  -4.  -5.   4.   6.]


Exercise-28

In [ ]:
Z = np.random.uniform(0,10,10) 
print (Z - Z%1) 
print (np.floor(Z)) 
print (np.ceil(Z)-1) 


[7. 8. 0. 5. 3. 9. 2. 1. 6. 5.]
[7. 8. 0. 5. 3. 9. 2. 1. 6. 5.]
[7. 8. 0. 5. 3. 9. 2. 1. 6. 5.]


Exercise-29

In [ ]:
Z = np.zeros((5,5)) 
Z += np.arange(5) 
print(Z) 


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Exercise-30

In [ ]:
def generate(): 
    for x in range(10): 
        yield x 
Z = np.fromiter(generate(),dtype=float,count=-1) 
print(Z) 





[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Exercise-31

In [ ]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1] 
print(Z) 


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Exercise-32

In [ ]:
Z = np.random.random(10) 
Z.sort() 
print(Z) 


[0.20516168 0.41661472 0.44107528 0.49435436 0.58023895 0.70251361
 0.76890941 0.76937944 0.80742709 0.98039237]


Exercise-33

In [ ]:
Z = np.arange(10) 
np.add.reduce(Z) 


45

Exercise-34

In [ ]:
A = np.random.randint(0,2,5) 
B = np.random.randint(0,2,5) 
equal = np.allclose(A,B) 
print(equal) 


False


Exercise-35

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = True
Z[0] = 1

Exercise-36

In [ ]:
Z = np.random.random((10,2)) 
X,Y = Z[:,0], Z[:,1] 
R = np.sqrt(X**2+Y**2) 
T = np.arctan2(Y,X) 
print(R) 
print(T) 


[1.04432529 0.71584029 1.09459706 0.50873731 0.25823853 1.01095182
 0.84504827 0.51251595 0.62662089 1.07422889]
[0.30892366 1.10975244 1.13930678 0.66978921 0.6444251  0.34173975
 1.40486817 1.20928769 0.85317824 0.80116596]


Exercise-37

In [ ]:
Z = np.random.random(10) 
Z[Z.argmax()] = 0 
print(Z) 


[0.85974221 0.94681296 0.         0.99635829 0.3349113  0.85098835
 0.12775303 0.4244272  0.91906556 0.79172669]


Exercise-38

In [ ]:
Z = np.zeros((10,10), [('x',float),('y',float)]) 
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10), 
np.linspace(0,1,10)) 
print(Z)


[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

Exercise-39

In [ ]:
X = np.arange(8) 
Y = X + 0.5 
C = 1.0 / np.subtract.outer(X, Y) 
print(np.linalg.det(C)) 


3638.163637117973


Exercise-40

In [ ]:
import numpy as np
for dtype in [np.int8, np.int32, np.int64]: 
    print(np.iinfo(dtype).min),
    print(np.iinfo(dtype).max) 
for dtype in [np.float32, np.float64]: 
    print(np.finfo(dtype).min) 
    print(np.finfo(dtype).max) 
    print(np.finfo(dtype).eps) 



-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


Exercise-41


In [ ]:
np.set_printoptions(threshold=np.nan) 
Z = np.zeros((25,25)) 
print(Z) 
 


ValueError: ignored

Exercise-42

In [ ]:
Z = np.arange(100) 
v = np.random.uniform(0,100) 
index = (np.abs(Z-v)).argmin() 
print(Z[index]) 


1


Exercise-43

In [ ]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float, 1), 
('y', float, 1)]), 
('color', [ ('r', float, 1), 
('g', float, 1), 
('b', float, 1)])]) 
print(Z) 



[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


Exercise-44

In [ ]:
Z = np.random.random((10,2)) 
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1]) 
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2) 
print(D) 


[[0.         0.36798289 0.79143364 0.46402561 0.65936378 0.67227031
  0.17953607 0.61696664 0.10915524 0.78806885]
 [0.36798289 0.         0.44614014 0.27081281 0.3734023  0.36822618
  0.345048   0.45316303 0.36816934 0.42062814]
 [0.79143364 0.44614014 0.         0.39336446 0.20506235 0.50156789
  0.79110323 0.42145827 0.75478632 0.2365871 ]
 [0.46402561 0.27081281 0.39336446 0.         0.21096428 0.59408084
  0.53681237 0.18487218 0.39587961 0.50959766]
 [0.65936378 0.3734023  0.20506235 0.21096428 0.         0.57849398
  0.70079674 0.21906889 0.60196843 0.39119693]
 [0.67227031 0.36822618 0.50156789 0.59408084 0.57849398 0.
  0.55820992 0.74897501 0.7095158  0.29854903]
 [0.17953607 0.345048   0.79110323 0.53681237 0.70079674 0.55820992
  0.         0.71230088 0.27944576 0.73408741]
 [0.61696664 0.45316303 0.42145827 0.18487218 0.21906889 0.74897501
  0.71230088 0.         0.5309347  0.60409769]
 [0.10915524 0.36816934 0.75478632 0.39587961 0.60196843 0.7095158
  0.27944576 0.530934

In [ ]:
Z = np.random.random((10,2)) 
D = (0,1) 
print(D) 


(0, 1)


Exercise-45

In [ ]:
Z = np.arange(10, dtype=np.int32) 
Z = Z.astype(np.float32, copy=False) 





Exercise-47

In [ ]:
Z = np.arange(9).reshape(3,3) 
for index, value in np.ndenumerate(Z): 
    print(index, value) 
for index in np.ndindex(Z.shape): 
    print(index, Z[index]) 



(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


Exercise-48

In [ ]:
D = np.sqrt(X*X+Y*Y) 
sigma, mu = 1.0, 0.0 
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) ) 
print(G) 


[[0.6800825  0.80258793 0.91410127 0.91412495 0.9537642  0.67786669
  0.6305149  0.96573457 0.72923475 0.80595112]]


Exercise-49

In [ ]:
import numpy as np
n = 10 
p = 3 
Z = np.zeros((n,n)) 
np.put(Z, np.random.choice(range(n*n), p, replace=1),1) 



Exercise-50

In [ ]:
X = np.random.rand(5, 10) 
Y = X - X.mean(axis=1, keepdims=True) 



Exercise-51

In [ ]:
Z = np.random.randint(0,10,(3,3)) 
print(Z) 
print(Z[Z[:,1].argsort()]) 


[[5 3 0]
 [4 1 4]
 [3 1 7]]
[[4 1 4]
 [3 1 7]
 [5 3 0]]


Exercise-52

In [ ]:
Z = np.random.randint(0,3,(3,10)) 
print((~Z.any(axis=0)).any()) 


False


Exercise-53

In [ ]:
Z = np.random.uniform(0,1,10) 
z = 0.5 
m = Z.flat[np.abs(Z - z).argmin()] 
print(m) 


0.5979927035316106


Exercise-54

In [ ]:
Z =(np.arange(10), "range_10")
Z = (np.arange(10), "range_10") 
print (Z) 


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'range_10')


Exercise-55

In [ ]:
Z = np.ones(10) 
I = np.random.randint(0,len(Z),20) 
Z += np.bincount(I, minlength=len(Z)) 
print(Z) 


[4. 4. 2. 2. 1. 4. 3. 2. 4. 4.]


Exercise-56

In [ ]:
X = [1,2,3,4,5,6] 
I = [1,3,9,3,4,1] 
F = np.bincount(I,X) 
print(F) 


[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


Exercise-57

In [ ]:
w,h = 16,16 
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte) 
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2] 
n = len(np.unique(F)) 
print(np.unique(I)) 


[0 1]


Exercise-58

In [ ]:
A = np.random.randint(0,10,(3,4,3,4)) 
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1) 
print(sum) 


[[55 45 60 52]
 [53 64 58 56]
 [45 53 48 63]]


Exercise-59

In [ ]:
D = np.random.uniform(0,1,100) 
S = np.random.randint(0,10,100) 
D_sums = np.bincount(S, weights=D) 
D_counts = np.bincount(S) 
D_means = D_sums / D_counts 
print(D_means) 


[0.56490586 0.5616153  0.52177868 0.48663561 0.52587527 0.60783106
 0.44965175 0.6133393  0.49180775 0.34984975]


Exerxice-60

In [22]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


array([0.74743285, 0.59752508, 0.88685589, 1.75692082, 1.09985651])

Exercise-61

In [23]:
Z = np.array([1,2,3,4,5]) 
nz = 3 
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz)) 
Z0[::nz+1] = Z 
print(Z0) 


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Exercise-62

In [24]:
A = np.ones((5,5,3)) 
B = 2*np.ones((5,5)) 
print(A * B[:,:,None]) 


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


Exercise-63

In [25]:
A = np.arange(25).reshape(5,5) 
A[[0,1]] = A[[1,0]] 
print(A) 


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Exercise-64

In [26]:
faces = np.random.randint(0,100,(10,3)) 
F = np.roll(faces.repeat(2,axis=1),-1,axis=1) 
F = F.reshape(len(F)*3,2) 
F = np.sort(F,axis=1) 
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] ) 
G = np.unique(G) 
print(G) 


[( 6, 69) ( 6, 82) ( 8, 18) ( 8, 77) (10, 33) (10, 36) (18, 65) (18, 77)
 (18, 80) (22, 41) (22, 87) (25, 73) (25, 88) (31, 33) (31, 84) (33, 36)
 (33, 84) (41, 87) (52, 80) (52, 98) (61, 72) (61, 96) (65, 80) (69, 82)
 (72, 96) (73, 88) (80, 98) (86, 90) (90, 90)]


Exercise-65

In [27]:
C = np.bincount([1,1,2,3,4,4,6]) 
A = np.repeat(np.arange(len(C)), C) 
print(A) 


[1 1 2 3 4 4 6]


Exercise-66

In [29]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


Exercise-67

In [31]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


Exercise-68

In [33]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([ 0.71143134,  0.56899632,  0.05440354, -0.3416795 ,  0.21551624,
       -0.06143306, -0.72898258,  0.84141328,  0.6872884 ,  0.44649189,
        0.16761279,  0.30159372,  0.44283942, -0.23839679,  0.84530948,
        0.15465973,  0.09497181, -0.05012094,  0.84469461, -0.11336304,
        0.20285225,  0.16543067,  0.36054913, -0.62947978, -0.1996265 ,
        0.68640058, -0.02854576,  0.87807972,  0.42274696, -0.8318396 ,
        0.33995744,  0.78891022, -0.09928659,  0.36903107,  0.56571359,
       -0.27805991, -0.2262344 ,  0.49346596,  0.65228156, -0.12564414,
       -0.92392764,  0.04323074, -0.71951832,  0.32717857,  0.0344122 ,
        0.45218518,  0.34355373,  0.90894001,  0.90627113, -0.45401592,
       -0.88101924,  0.03487606,  0.78724223,  0.64120263,  0.17434811,
        0.82774244, -0.46434745, -0.01459127,  0.76442925,  0.66025024,
        0.88710487, -0.3372794 ,  0.86938709, -0.71030111,  0.1674583 ,
        0.33775251,  0.8300904 ,  0.49029821,  0.73362038,  0.85

Exercise-69

In [35]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.36548757 11.9274221  12.78157359  2.72041374  2.41707758  7.18284294
  8.8603867   3.71818476  8.95591217  2.24202283]


Exercise-70

In [37]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.11143186  2.37222511  5.10294183  0.0626456   4.76896022  4.05233119
   6.46990582  2.68695851  0.37956592  1.4651045 ]
 [ 9.78549374 12.77014379  3.90166847  0.01846009  4.11418302  0.77679878
  15.49081993 13.0848231   8.12438287  0.79289669]
 [ 6.71348601  2.28219756  0.78723706  6.22760031 10.04826515 10.55044595
   8.2239742   2.59703559  1.8648755   7.91940882]
 [ 6.35195684  1.74635644  0.69696946  6.20024666 10.48103873 10.68814801
   7.7502884   2.06119676  1.41549521  8.00484217]
 [ 7.43829433  3.66416478 16.5623882  11.15525961  0.43732655  5.84627512
   2.10877949  3.34958996  9.54436018  8.96038038]
 [ 3.31379589  2.59580354  4.98221981  0.16083295  4.6616167   4.08594527
   6.69334024  2.91053745  0.15943331  1.5200349 ]
 [ 5.84775112  9.85595667  8.30581075  1.75562743 13.63740694  5.9416058
   4.6947414   9.54119127 11.0836642   2.16835855]
 [13.31926196  8.73300069  5.50706884 10.3525798   8.0414969  12.87628584
  15.05462546  9.04787532  8.70209995 10.85294273]
 