<a href="https://colab.research.google.com/github/maharajsreeraam/groupcodesof214519/blob/main/CIE_3___214519_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np

Exercise-2

In [ ]:
import numpy as np
print(np.__version__) 
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

Exercise-3

In [ ]:
import numpy as np
Z = np.zeros(10) 
print(Z) 




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Exercise-4

In [ ]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
Z = np.zeros(10) 
Z[5] = 2 
print(Z) 


[0. 0. 0. 0. 0. 2. 0. 0. 0. 0.]


In [ ]:
Z = np.arange(20,50) 
print(Z) 


[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [ ]:
Z = np.arange(50) 
Z[::-1] 


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
Z = np.arange(9).reshape(3,3) 
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


Exercise-10

In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Exercise-11

In [ ]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.83872722 0.72931184 0.43787498]
  [0.44719527 0.97688515 0.44279211]
  [0.87564006 0.83325934 0.82837973]]

 [[0.55144577 0.70225548 0.18665083]
  [0.58724493 0.48295483 0.6381489 ]
  [0.65216714 0.67383747 0.18711105]]

 [[0.28072657 0.94923364 0.76618248]
  [0.98362719 0.19023442 0.12250561]
  [0.49106761 0.57762108 0.14881921]]]


Exercise-12

In [ ]:
Z = np.random.random((10,10))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

[[0.16189584 0.50575723 0.0537293  0.12253594 0.83411932 0.34006094
  0.01727421 0.30725442 0.28146674 0.40487759]
 [0.45615227 0.71109881 0.07023555 0.50102184 0.69917754 0.61033765
  0.4791942  0.60928028 0.2983793  0.69936112]
 [0.58181094 0.22851674 0.63348995 0.58180965 0.65640054 0.40621607
  0.03703532 0.95484036 0.38477928 0.53672952]
 [0.84443117 0.11086394 0.16788903 0.65604075 0.40037017 0.01491978
  0.97469814 0.08649354 0.25696141 0.7189334 ]
 [0.46109349 0.75914963 0.39210626 0.06840445 0.16474603 0.65108513
  0.54367103 0.33059165 0.0324063  0.7698414 ]
 [0.79435424 0.77711709 0.02782988 0.40794359 0.14561257 0.16194776
  0.73277521 0.0625606  0.79579685 0.69081332]
 [0.81753288 0.77419249 0.74679353 0.13405246 0.59667643 0.80869201
  0.97895656 0.88461045 0.43433227 0.55483528]
 [0.07181995 0.47212708 0.35003323 0.08471504 0.59622032 0.17158773
  0.73668726 0.36884274 0.63509903 0.1194443 ]
 [0.87417941 0.06099371 0.65526328 0.86331111 0.55099622 0.60017749
  0.23827451

Exercise-13

In [ ]:
Z = np.random.random(20) 
m = Z.mean() 
print(m)


0.47109583862641385


Exercise-14

In [ ]:
Z = np.ones((10,10)) 
Z[1:-1,1:-1] = 0 


Exercise-15

In [ ]:
import numpy as np
0 * np.nan 
np.nan == np.nan 
np.inf > np.nan 
np.nan - np.nan 
0.3 == 3 * 0.1 


False

Exercise-16

In [ ]:
Z = np.diag(1+np.arange(4),k=-1) 
print(Z) 


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Exercise-17

In [ ]:
import numpy as np

In [ ]:
Z = np.zeros((8,8),dtype=int) 
Z[1::2,::2] = 1 
Z[::2,1::2] = 1 
print(Z) 


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Exercise-18

In [ ]:
print(np.unravel_index(100,(6,7,8))) 


(1, 5, 4)


Exercise-19

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4)) 
print(Z) 


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Exercise-20

In [ ]:
Z = np.random.random((5,5)) 
Zmax, Zmin = Z.max(), Z.min() 
Z = (Z - Zmin)/(Zmax - Zmin) 
print(Z) 


[[0.08188229 1.         0.42731889 0.45880991 0.84091554]
 [0.82161523 0.         0.89721332 0.09221291 0.3013733 ]
 [0.70908716 0.92500281 0.58246459 0.4900201  0.70566889]
 [0.93384672 0.19638451 0.52001085 0.15971426 0.78837178]
 [0.9780057  0.8278211  0.8019057  0.27045547 0.10289927]]


Exercise-21

In [ ]:
color = np.dtype([("r", np.ubyte, 1), 
("g", np.ubyte, 1), 
("b", np.ubyte, 1), 
("a", np.ubyte, 1)]) 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


Exercise-22

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2))) 
print(Z) 


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Exercise-23

In [ ]:
import numpy as np
Z = np.arange(11) 
Z[(3 < Z) & (Z <= 8)]


array([4, 5, 6, 7, 8])

Exercise-24

In [ ]:
print(sum(range(5),-1)) 
from numpy import * 
print(sum(range(5),-1)) 



9
10


Exercise-25

In [ ]:
import numpy as np
Z**Z 
2 << Z >> 2 
Z <- Z 
1j*Z 
Z/1/1 



array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Exercise-26

In [ ]:
np.array(0) // np.array(0) 
np.array(0) // np.array(0.) 
np.array(0) / np.array(0) 
np.array(0) / np.array(0.) 

 


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in floor_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


nan

Exercise-27

In [ ]:
Z = np.random.uniform(-10,+10,10) 
print (np.trunc(Z + np.copysign(0.5, Z))) 


[ -9.   7.  -1.  -9. -10.   3.  -4.  -5.   4.   6.]


Exercise-28

In [ ]:
Z = np.random.uniform(0,10,10) 
print (Z - Z%1) 
print (np.floor(Z)) 
print (np.ceil(Z)-1) 


[7. 8. 0. 5. 3. 9. 2. 1. 6. 5.]
[7. 8. 0. 5. 3. 9. 2. 1. 6. 5.]
[7. 8. 0. 5. 3. 9. 2. 1. 6. 5.]


Exercise-29

In [ ]:
Z = np.zeros((5,5)) 
Z += np.arange(5) 
print(Z) 


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Exercise-30

In [ ]:
def generate(): 
    for x in range(10): 
        yield x 
Z = np.fromiter(generate(),dtype=float,count=-1) 
print(Z) 





[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Exercise-31

In [ ]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1] 
print(Z) 


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Exercise-32

In [ ]:
Z = np.random.random(10) 
Z.sort() 
print(Z) 


[0.20516168 0.41661472 0.44107528 0.49435436 0.58023895 0.70251361
 0.76890941 0.76937944 0.80742709 0.98039237]


Exercise-33

In [ ]:
Z = np.arange(10) 
np.add.reduce(Z) 


45

Exercise-34

In [ ]:
A = np.random.randint(0,2,5) 
B = np.random.randint(0,2,5) 
equal = np.allclose(A,B) 
print(equal) 


False


Exercise-35

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = True
Z[0] = 1

Exercise-36

In [ ]:
Z = np.random.random((10,2)) 
X,Y = Z[:,0], Z[:,1] 
R = np.sqrt(X**2+Y**2) 
T = np.arctan2(Y,X) 
print(R) 
print(T) 


[1.04432529 0.71584029 1.09459706 0.50873731 0.25823853 1.01095182
 0.84504827 0.51251595 0.62662089 1.07422889]
[0.30892366 1.10975244 1.13930678 0.66978921 0.6444251  0.34173975
 1.40486817 1.20928769 0.85317824 0.80116596]


Exercise-37

In [ ]:
Z = np.random.random(10) 
Z[Z.argmax()] = 0 
print(Z) 


[0.85974221 0.94681296 0.         0.99635829 0.3349113  0.85098835
 0.12775303 0.4244272  0.91906556 0.79172669]
